# Generated by Django 2.2.1 on 2019-06-21 16:43

import akshayaindiawebsite.models
import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AskQuestionEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Process', 'Process'), ('Resolved', 'Resolved')], default='Pending', max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('question_type', models.CharField(max_length=120)),
                ('your_question', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(unique=True)),
                ('short_desc', models.TextField()),
                ('hero_blog', models.BooleanField(default=False)),
                ('home_visible', models.BooleanField(default=False)),
                ('banner_image', models.FileField(upload_to=akshayaindiawebsite.models.Blog.banner_image_path)),
                ('card_image', models.FileField(upload_to=akshayaindiawebsite.models.Blog.card_image_path)),
                ('blog_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Process', 'Process'), ('Resolved', 'Resolved')], default='Pending', max_length=64)),
                ('type_of_requirement', models.CharField(max_length=20)),
                ('pick_up_from', models.CharField(max_length=120)),
                ('drop_at', models.CharField(max_length=20)),
                ('date_of_journey', models.DateField()),
                ('vehical_type', models.CharField(max_length=20)),
                ('number_of_adult', models.CharField(default=0, max_length=10)),
                ('number_of_children', models.CharField(default=0, max_length=10)),
                ('additional_request', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('phone_number', models.CharField(max_length=13)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Process', 'Process'), ('Resolved', 'Resolved')], default='Pending', max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CorporateConference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=120)),
                ('heading_image', models.FileField(upload_to=akshayaindiawebsite.models.CorporateConference.heading_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='CorporateEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Process', 'Process'), ('Resolved', 'Resolved')], default='Pending', max_length=64)),
                ('type_of_work', models.CharField(max_length=120)),
                ('company_name', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('phone_number', models.CharField(max_length=13)),
                ('additional_request', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CorporateHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetings_content', ckeditor.fields.RichTextField()),
                ('conferences_content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='CorporateMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=120)),
                ('heading_image', models.FileField(upload_to=akshayaindiawebsite.models.CorporateMeeting.heading_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='FlightEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Process', 'Process'), ('Resolved', 'Resolved')], default='Pending', max_length=64)),
                ('travel_from', models.CharField(max_length=120)),
                ('travel_to', models.CharField(max_length=120)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('number_of_adult', models.CharField(blank=True, max_length=10, null=True)),
                ('number_of_children', models.CharField(blank=True, max_length=10, null=True)),
                ('number_of_infant', models.CharField(blank=True, max_length=10, null=True)),
                ('Class', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('phone_number', models.CharField(max_length=13)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HotelEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Process', 'Process'), ('Resolved', 'Resolved')], default='Pending', max_length=64)),
                ('destination', models.CharField(max_length=120)),
                ('number_of_room', models.CharField(max_length=20)),
                ('number_of_adult', models.CharField(max_length=20)),
                ('number_of_children', models.CharField(max_length=20)),
                ('additional_request', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('phone_number', models.CharField(max_length=13)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('photo', models.FileField(upload_to=akshayaindiawebsite.models.Testimonial.card_image_path)),
                ('words', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(unique=True)),
                ('tour_type', models.CharField(choices=[('India', 'India'), ('International', 'International'), ('Cruise', 'Cruise')], max_length=20)),
                ('home_visible', models.BooleanField(default=False)),
                ('high_demand', models.BooleanField(default=False)),
                ('hero_tour', models.BooleanField(default=False)),
                ('tour_price', models.CharField(max_length=16)),
                ('tour_discounted_price', models.CharField(blank=True, max_length=16, null=True)),
                ('tour_duration', models.IntegerField()),
                ('day_in_tour', models.IntegerField()),
                ('night_in_tour', models.IntegerField()),
                ('banner_image', models.FileField(upload_to=akshayaindiawebsite.models.Vacation.banner_image_path)),
                ('card_image', models.FileField(upload_to=akshayaindiawebsite.models.Vacation.card_image_path)),
                ('overview_content', ckeditor.fields.RichTextField()),
                ('experience_content', ckeditor.fields.RichTextField()),
                ('information_content', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Vacation',
                'verbose_name_plural': 'Vacations',
            },
        ),
        migrations.CreateModel(
            name='VacationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=256)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.CharField(max_length=16)),
                ('banner_image', models.FileField(upload_to=akshayaindiawebsite.models.Visa.banner_image_path)),
                ('card_image', models.FileField(upload_to=akshayaindiawebsite.models.Visa.card_image_path)),
                ('document', models.FileField(upload_to=akshayaindiawebsite.models.Visa.visa_document_path)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Visa',
                'verbose_name_plural': 'Visas',
            },
        ),
        migrations.CreateModel(
            name='VisaFAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answere', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akshayaindiawebsite.Visa')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VisaEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Process', 'Process'), ('Resolved', 'Resolved')], default='Pending', max_length=64)),
                ('type_of_visa', models.CharField(max_length=120)),
                ('city_of_residence', models.CharField(max_length=120)),
                ('date_of_travel', models.DateField()),
                ('additional_request', models.TextField()),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('phone_number', models.CharField(max_length=13)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akshayaindiawebsite.Visa')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VacationService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=256)),
                ('vacation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akshayaindiawebsite.Vacation')),
            ],
        ),
        migrations.CreateModel(
            name='VacationEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_from', models.CharField(max_length=120)),
                ('travel_to', models.CharField(max_length=120)),
                ('travel_mode', models.CharField(max_length=120)),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('number_of_adult', models.CharField(max_length=10)),
                ('number_of_children', models.CharField(max_length=10)),
                ('number_of_infant', models.CharField(max_length=10)),
                ('Class', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Process', 'Process'), ('Resolved', 'Resolved')], default='Pending', max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('phone_number', models.CharField(max_length=13)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vacation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akshayaindiawebsite.Vacation')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='vacation',
            name='category',
            field=models.ManyToManyField(to='akshayaindiawebsite.VacationCategory'),
        ),
        migrations.CreateModel(
            name='TypesOfVisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_name', models.CharField(max_length=120)),
                ('processing_time', models.CharField(max_length=120)),
                ('stay_period', models.CharField(max_length=120)),
                ('validity', models.CharField(max_length=120)),
                ('entry', models.CharField(max_length=120)),
                ('fees', models.CharField(max_length=120)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_type', to='akshayaindiawebsite.Visa')),
            ],
        ),
        migrations.CreateModel(
            name='ItinerarySectionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=120)),
                ('breakfast', models.BooleanField(default=False)),
                ('lunch', models.BooleanField(default=False)),
                ('dinner', models.BooleanField(default=False)),
                ('stay_in_hotel', models.BooleanField(default=False)),
                ('vacation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akshayaindiawebsite.Vacation')),
            ],
        ),
        migrations.CreateModel(
            name='GallaryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallary_image', models.FileField(upload_to=akshayaindiawebsite.models.GallaryModel.gallary_image_path)),
                ('vacation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akshayaindiawebsite.Vacation')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('Tours', 'Tours'), ('Visa', 'Visa'), ('Hotels', 'Hotels'), ('Cars', 'Cars'), ('Couple', 'Couple'), ('Packages', 'Packages')], max_length=20)),
                ('question', models.TextField()),
                ('answere', models.TextField()),
                ('helpful', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(to='akshayaindiawebsite.FAQCategory')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BlogGallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallary', models.FileField(upload_to=akshayaindiawebsite.models.BlogGallary.gallary_image_path)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akshayaindiawebsite.Blog')),
            ],
        ),
    ]
