# Generated by Django 2.2.1 on 2019-06-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0002_itinerarysectionmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarysectionmodel',
            name='description1',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
