# Generated by Django 2.2.1 on 2019-06-22 14:46

import akshayaindiawebsite.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0004_auto_20190622_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallarymodel',
            name='gallary_image',
            field=models.ImageField(upload_to=akshayaindiawebsite.models.GallaryModel.gallary_image_path),
        ),
        migrations.AlterField(
            model_name='gallarymodel',
            name='vacation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='akshayaindiawebsite.Vacation'),
        ),
    ]
