# Generated by Django 2.2.1 on 2019-06-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0005_auto_20190622_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='tour_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
