# Generated by Django 2.2.1 on 2019-06-25 11:38

import akshayaindiawebsite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0006_auto_20190622_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=120)),
                ('heading_image', models.FileField(upload_to=akshayaindiawebsite.models.CorporateEvent.heading_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='CorporateIncentives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=120)),
                ('heading_image', models.FileField(upload_to=akshayaindiawebsite.models.CorporateIncentives.heading_image_path)),
            ],
        ),
    ]
