# Generated by Django 2.2.1 on 2019-06-25 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0007_corporateevent_corporateincentives'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateevent',
            name='corporate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='akshayaindiawebsite.CorporateHeading'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corporateincentives',
            name='corporate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='akshayaindiawebsite.CorporateHeading'),
            preserve_default=False,
        ),
    ]
