# Generated by Django 2.2.1 on 2019-06-25 15:20

import akshayaindiawebsite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0008_auto_20190625_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateevent',
            name='heading_image',
            field=models.ImageField(upload_to=akshayaindiawebsite.models.CorporateEvent.heading_image_path),
        ),
        migrations.AlterField(
            model_name='corporateincentives',
            name='heading_image',
            field=models.ImageField(upload_to=akshayaindiawebsite.models.CorporateIncentives.heading_image_path),
        ),
    ]
