# Generated by Django 2.2.1 on 2019-06-25 17:57

import akshayaindiawebsite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0009_auto_20190625_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateevent',
            name='heading_image',
            field=models.FileField(upload_to=akshayaindiawebsite.models.CorporateEvent.heading_image_path),
        ),
        migrations.AlterField(
            model_name='corporateincentives',
            name='heading_image',
            field=models.FileField(upload_to=akshayaindiawebsite.models.CorporateIncentives.heading_image_path),
        ),
    ]
