# Generated by Django 2.2.1 on 2019-06-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0011_auto_20190627_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typesofvisa',
            name='entry',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='typesofvisa',
            name='fees',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='typesofvisa',
            name='processing_time',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='typesofvisa',
            name='stay_period',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='typesofvisa',
            name='validity',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='typesofvisa',
            name='visa_name',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
