# Generated by Django 2.2.1 on 2019-07-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0014_auto_20190629_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carenquiry',
            name='additional_request',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='corporateenquiry',
            name='additional_request',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hotelenquiry',
            name='additional_request',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='visaenquiry',
            name='additional_request',
            field=models.CharField(max_length=255),
        ),
    ]
