# Generated by Django 2.2.1 on 2019-07-05 18:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0015_auto_20190703_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerarysectionmodel',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
