# Generated by Django 2.2.1 on 2019-07-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0016_auto_20190705_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerarysectionmodel',
            name='description',
            field=models.TextField(),
        ),
    ]
