# Generated by Django 2.2.1 on 2019-07-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0017_auto_20190705_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='short',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
