# Generated by Django 2.2.1 on 2019-07-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0018_testimonial_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='short',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
