# Generated by Django 2.2.1 on 2019-07-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0020_auto_20190711_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerarysectionmodel',
            name='breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itinerarysectionmodel',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itinerarysectionmodel',
            name='dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itinerarysectionmodel',
            name='heading',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itinerarysectionmodel',
            name='lunch',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itinerarysectionmodel',
            name='stay_in_hotel',
            field=models.BooleanField(default=False),
        ),
    ]
