# Generated by Django 2.2.1 on 2019-07-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0021_auto_20190711_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation',
            name='high_demand',
        ),
        migrations.AddField(
            model_name='vacation',
            name='vacation_label',
            field=models.CharField(blank=True, choices=[('High Demand', 'High Demand'), ('Trending', 'Trending'), ('New', 'New')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='slug',
            field=models.SlugField(max_length=256, unique=True),
        ),
    ]
