# Generated by Django 2.2.1 on 2019-07-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0022_auto_20190712_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='vacation_label',
            field=models.CharField(blank=True, choices=[('High Demand', 'High Demand'), ('Trending', 'Trending'), ('Best Seller', 'Best Seller')], max_length=20, null=True),
        ),
    ]
