# Generated by Django 2.2.1 on 2019-07-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0023_auto_20190713_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='price',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
