# Generated by Django 2.2.1 on 2019-07-14 13:34

import akshayaindiawebsite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0024_auto_20190714_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateevent',
            name='heading',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='corporateevent',
            name='heading_image',
            field=models.FileField(blank=True, null=True, upload_to=akshayaindiawebsite.models.CorporateEvent.heading_image_path),
        ),
        migrations.AlterField(
            model_name='corporateincentives',
            name='heading_image',
            field=models.FileField(blank=True, null=True, upload_to=akshayaindiawebsite.models.CorporateIncentives.heading_image_path),
        ),
    ]
