# Generated by Django 2.2.1 on 2019-07-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0025_auto_20190714_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateincentives',
            name='heading',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
