# Generated by Django 2.2.1 on 2019-07-15 19:03

import akshayaindiawebsite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0027_vacation_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=akshayaindiawebsite.models.Visa.visa_document_path),
        ),
    ]
