# Generated by Django 2.2.1 on 2019-07-16 11:53

import akshayaindiawebsite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0028_auto_20190715_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationcategory',
            name='gallary',
            field=models.FileField(default=1, upload_to=akshayaindiawebsite.models.VacationCategory.category_icon_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacationcategory',
            name='short_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacationcategory',
            name='category_name',
            field=models.CharField(max_length=255),
        ),
    ]
