# Generated by Django 2.2.1 on 2019-07-16 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0029_auto_20190716_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacationcategory',
            old_name='gallary',
            new_name='icon',
        ),
    ]
