# Generated by Django 2.2.1 on 2019-07-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0034_auto_20190727_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationenquiry',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
