# Generated by Django 2.2.1 on 2019-07-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0035_auto_20190727_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationenquiry',
            name='phone_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
