# Generated by Django 2.2.1 on 2019-07-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0037_auto_20190728_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarysectionmodel',
            name='itenary_order',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
