# Generated by Django 2.2.1 on 2019-07-29 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0038_itinerarysectionmodel_itenary_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerarysectionmodel',
            name='itenary_order',
        ),
    ]
