# Generated by Django 2.2.1 on 2019-07-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0039_remove_itinerarysectionmodel_itenary_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carenquiry',
            name='additional_request',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carenquiry',
            name='date_of_journey',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carenquiry',
            name='drop_at',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='carenquiry',
            name='number_of_adult',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='carenquiry',
            name='number_of_children',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='carenquiry',
            name='vehical_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
