# Generated by Django 2.2.1 on 2019-07-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0041_auto_20190729_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaenquiry',
            name='additional_request',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visaenquiry',
            name='city_of_residence',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='visaenquiry',
            name='date_of_travel',
            field=models.DateField(blank=True, null=True),
        ),
    ]
