# Generated by Django 2.2.1 on 2019-07-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0042_auto_20190729_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelenquiry',
            name='number_of_adult',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
