# Generated by Django 2.2.1 on 2019-07-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0043_auto_20190731_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carenquiry',
            name='number_of_adult',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='carenquiry',
            name='number_of_children',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
