# Generated by Django 2.2.1 on 2019-07-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0044_auto_20190731_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carenquiry',
            name='date_of_journey',
            field=models.DateField(),
        ),
    ]
