# Generated by Django 2.2.1 on 2019-07-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0045_auto_20190731_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carenquiry',
            name='drop_at',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carenquiry',
            name='pick_up_from',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='carenquiry',
            name='type_of_requirement',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='carenquiry',
            name='vehical_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
