# Generated by Django 2.2.1 on 2019-07-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0046_auto_20190731_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationenquiry',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
    ]
