# Generated by Django 2.2.1 on 2019-08-01 21:58

import akshayaindiawebsite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0047_auto_20190731_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallarymodel',
            name='gallary_image',
            field=models.FileField(blank=True, null=True, upload_to=akshayaindiawebsite.models.GallaryModel.gallary_image_path),
        ),
    ]
