# Generated by Django 2.2.1 on 2019-08-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akshayaindiawebsite', '0048_auto_20190801_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerarysectionmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itinerarysectionmodel',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
